"""Добавил колонку для теста

Revision ID: 078cac6df821
Revises: 227a00851057
Create Date: 2025-04-23 09:00:44.778818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078cac6df821'
down_revision = '227a00851057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
