"""status tasks

Revision ID: 0d701a693cd2
Revises: cae17b32fc67
Create Date: 2025-04-26 02:41:31.646775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d701a693cd2'
down_revision = 'cae17b32fc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
        # Для автоматической проставки данных в новую колонку
        batch_op.add_column(
            sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
