"""Комментарий, что поменял

Revision ID: 227a00851057
Revises: 
Create Date: 2025-04-23 08:50:46.292859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227a00851057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
